
GET http://localhost:3000

### Recuperar todas las peliculas
GET http://localhost:3000/movies

### recuperar una pelicula por id
GET http://localhost:3000/movies/241bf55d-b649-4109-af7c-0e6890ded3fc

### 
GET http://localhost:3000/movies/5/terror/2020

### Recuperar peliculas por genero
GET http://localhost:3000/movies?genre=action

### Recuperar peliculas por genero
GET http://localhost:3000/movies?year=2012

###
GET http://localhost:3000/movies?genre=Action&year=2008

### Crear una pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
      "Crime",
      "Drama"
      ],
    "sql": "SELECT * FROM users"
}

### Actualizar una pelicula con PATCH enlugar de PUT
PATCH http://localhost:3000/movies/390efef8-82b5-4681-9ff9-d1395c3bc9c2
Content-Type: application/json

{
    "id": "5",
    "title": "Hola",
    "year": 1993
}

### Actualizar una pelicula con PUT: Es idempotente  
PUT http://localhost:3000/movies/390efef8-82b5-4681-9ff9-d1395c3bc9c2
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
      "Crime",
      "Drama"
      ],
    "sql": "SELECT * FROM users"
}